"use client"


import { Inter } from "next/font/google";
import "../globals.css";
import Sidenavbar from "./Navbar/sidenavbar";
import Uppernavbar from "./Navbar/uppernavbar";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const { user, error, isLoading } = useUser();
  const router = useRouter();
  const [isAdmin, setIsAdmin] = useState(null); // Track if the user is an admin

  // Check user role and redirect if necessary
  useEffect(() => {
    if (isLoading) return; // Wait until user is loaded

    if (!user) {
      router.push('/'); // Redirect to homepage if no user
      return;
    }

    const userRoles = user[`${process.env.AUTH0_BASE_URL}/roles`];
    if (!userRoles || !userRoles.includes('Admin')) {
      router.push('/'); // Redirect if not admin
      return;
    }

    setIsAdmin(true); // Set admin status to true if user is an admin
  }, [user, isLoading, router]);

  if (isLoading || isAdmin === null) return <div>Loading...</div>; // Show loading indicator while checking authentication

  if (error) return <div>Error: {error.message}</div>; // Handle any errors

  if (!isAdmin) return null; // Prevent rendering until admin check is complete

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full">
          <Sidenavbar />
          <div className="flex flex-col w-full">
            <Uppernavbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

{/*
import { Inter } from "next/font/google";
import "../globals.css";
import Sidenavbar from "./Navbar/sidenavbar";
import Uppernavbar from "./Navbar/uppernavbar";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRouter } from "next/navigation";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { user, error, isLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (isLoading) return;
    if (!user || !user['https://localhost:3000/roles'].includes('Admin')) {
      router.push("/"); // Redirect to Auth0 login page if not authenticated
    }
  }, [isLoading, user, router]);

  if (isLoading) return <div>Loading...</div>; // Show loading indicator while checking authentication

  if (error) return <div>Error: {error.message}</div>; // Handle any errors

  if (!user) return null; // Prevent rendering until the redirect is complete
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex w-full  ">
          <Sidenavbar />
          <div className="flex flex-col w-full">
            <Uppernavbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
*/}
